"""add_id_number_club_membership

Revision ID: 94565c01c960
Revises: b0ede4d6750e
Create Date: 2026-07-05 14:38:52.398863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94565c01c960'
down_revision: Union[str, Sequence[str], None] = 'b0ede4d6750e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('club_affiliation', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('membership_track', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'membership_track')
    op.drop_column('users', 'club_affiliation')
    op.drop_column('users', 'id_number')
    # ### end Alembic commands ###
