"""membership_tracks_json

Revision ID: 99977981cac4
Revises: 94565c01c960
Create Date: 2026-07-05 14:58:13.724035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99977981cac4'
down_revision: Union[str, Sequence[str], None] = '94565c01c960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('membership_tracks', sa.JSON(), nullable=True))
    op.drop_column('users', 'membership_track')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('membership_track', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('users', 'membership_tracks')
    # ### end Alembic commands ###
