"""add_user_profile_fields

Revision ID: b0ede4d6750e
Revises: 13b4eb6e945d
Create Date: 2026-07-05 14:17:24.607858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0ede4d6750e'
down_revision: Union[str, Sequence[str], None] = '13b4eb6e945d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('birth_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birth_year')
    op.drop_column('users', 'city')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
